/*
 *	Decks
 */

var humanoidUnarmed = new Array();
var humanoidSharp = new Array();
var humanoidBlunt = new Array();
var humanoidRanged = new Array();
var humanoidMelee = new Array();
var humanoidMonster = new Array();
var humanoidBarrier = new Array();
var humanoidHiding = new Array();

var beastUnarmed = new Array();
var beastSharp = new Array();
var beastBlunt = new Array();
var beastRanged = new Array();
var beastMelee = new Array();
var beastMonster = new Array();
var beastBarrier = new Array();
var beastHiding = new Array();

var eldritchUnarmed = new Array();
var eldritchSharp = new Array();
var eldritchBlunt = new Array();
var eldritchRanged = new Array();
var eldritchMelee = new Array();
var eldritchMonster = new Array();
var eldritchBarrier = new Array();
var eldritchHiding = new Array();

var soul = new Array();
var blood = new Array();
var shriveling = new Array();
var bind = new Array();

var fall = new Array();
var ties = new Array();
var classroom = new Array();
var sanctum = new Array();
var green = new Array();

/*
 *	Indices
 */

var iHumanoidUnarmed = 0;
var iHumanoidSharp = 0;
var iHumanoidBlunt = 0;
var iHumanoidRanged = 0;
var iHumanoidMonster = 0;
var iHumanoidBarrier = 0;
var iHumanoidHiding = 0;

var iBeastUnarmed = 0;
var iBeastSharp = 0;
var iBeastBlunt = 0;
var iBeastRanged = 0;
var iBeastMonster = 0;
var iBeastBarrier = 0;
var iBeastHiding = 0;

var iEldritchUnarmed = 0;
var iEldritchSharp = 0;
var iEldritchBlunt = 0;
var iEldritchRanged = 0;
var iEldritchMonster = 0;
var iEldritchBarrier = 0;
var iEldritchHiding = 0;

var iSoul = 0;
var iBlood = 0;
var iShriveling = 0;
var iBind = 0;

var iEvent = 0;
var iTime = 0;

/*
 *	Spells
 */

var soulSpell = '<div class="title">Soul Pact</div><div class="text">Choose 1 investigator in your room to heal 1 horror.</div><div class="test">Test Lore.</div>';
var bloodSpell = '<div class="title">Blood Pact</div><div class="text">Choose 1 investigator in your room to heal 1 damage.</div><div class="test">Test Lore.</div>';
var shrivelingSpell = '<div class="title">Shriveling</div><div class="text">Choose a monster within 2 range.</div><div class="test">Test Lore -1.</div>';
var bindSpell = '<div class="title">Bind Monster</div><div class="text">Choose a monster within 2 range.</div><div class="test">Test Lore.</div>';

soul[soul.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">The spell briefly allows you to focus on the task in front of you. The effect seems to pass quickly.</span> <span class="text">You retain the ability to cast Soul Pact.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You are overcome by fear and mistrust. You regret having ever dabbled in spellcraft.</span> <span class="text">You lose the ability to cast Soul Pact.</span></div>'
soul[soul.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">As the horrid memories of the recent past are focibly removed from your mind, your entire body shakes violently.</span> <span class="text">Heal 2 additional horror, and then take 1 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You are inside a coffin, buried alive and clawing at the lid. You snap out of this terrible illusion, but discover that your fingers are still bloodied.</span> <span class="text">Take 1 damage and 1 horror.</span></div>'
soul[soul.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">You hear gentle chimes and feel a cool breeze. They soothe your troubled mind.</span> <span class="text">Heal 1 additional horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You feel powerfully alert, your heart pounding in your chest and sweat pouring down your face.</span> <span class="text">Take 1 damage.</span></div>'
soul[soul.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">You feel the emotional weight of all your companions, depending on you for their well-being.</span> <span class="text">Every investigator in the room (not including yourself) heals 1 additional horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Time seems to stand still. It may have only been a minute, but you fear that much horror can be found within a single moment.</span> <span class="text">The keeper gains 3 threat.</span></div>'
soul[soul.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">In your mind\'s eye you see your entire life up to this point. You know in your heart that you are exactly where you are meant to be.</span> <span class="text">Discard 1 insanity Trauma card from any investigator in your room.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The entire room shakes ominously. You fear that strange forces conspire against you.</span> <span class="text">The keeper gains 3 threat.</span></div>'

blood[blood.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">The wounds have scarred over with a dark, rock-like substance.</span> <span class="text">Heal 2 additional damage, and then take 1 horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The wounds abruptly re-open and blood begins to spray out in a black and red mess.</span> <span class="text">Take 1 damage and 1 horror.</span></div>'
blood[blood.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">You feel the pact\'s healing energies sinking down into your bones, repairing your body all the way to your core.</span> <span class="text">Discard 1 injury Trauma card from any investigator in your room.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You feel as if your brain is on fire. The pain in your head overwhelms you.</span> <span class="text">The keeper may draw 1 Trauma card. Then take 1 horror.</span></div>'
blood[blood.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">Weariness washes away as your body begins to miraculously heal itself.</span> <span class="text">Heal 1 additional damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The skin around the recently healed wounds appears translucent and covered in an unidentified viscous slime.</span> <span class="text">Take 1 horror.</span></div>'
blood[blood.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">You feel the spell threaten to empty your lungs of air as it emanates from you.</span> <span class="text">Every investigator in the room (not including yourself) heals 1 additional damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">For a moment you lose control of your body. Your arms and legs move of their own accord.</span> <span class="text">The keeper may move you 1 space.</span></div>'
blood[blood.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">After the spell takes effect, it quickly dissipates.</span> <span class="text">You retain the ability to cast Blood Pact.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your face grows eerily pale and the room seems to be spinning.</span> <span class="text">You lose the ability to cast Blood Pact.</span></div>'

shriveling[shriveling.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">Small cuts appear all across your enemy\'s skin. It strikes itself repeatedly trying to escape the effect.</span> <span class="text">Deal an amount of damage to the monster equal to the monster\'s damage value +2.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Acrid black smoke billows out from the monster, as its skin bursts into flames.</span> <span class="text">Deal 2 damage, take 1 horror, and place a fire token in this room.</span></div>'
shriveling[shriveling.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">Your enemy\'s flesh pours off its body in a river of decay. You take comfort in knowing that it must be dead as you empty your stomach.</span> <span class="text">Take 1 horror. Then deal 7 damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">At first it appears that nothing is happening. A second later your vision blurs as you watch your enemy\'s skin boil.</span> <span class="text">Take 2 horror and deal 3 damage.</span></div>'
shriveling[shriveling.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">Your enemy\'s skin starts to rot before your very eyes, tearing it apart at a molecular level.</span> <span class="text">Take 1 horror and deal 5 damage. If the enemy is a humanoid monster, it is killed.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You sense that something has gone terribly wrong. The skin on your left hand stats to melt off.</span> <span class="text">Take 1 damage and 1 horror.</span></div>'
shriveling[shriveling.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">A shiver runs down your spine as the spell takes effect. Boils cover your enemy\'s body and it falls to the ground convulsing.</span> <span class="text">Deal 5 damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">As you finish the incantation, you wait as absolutely nothing happens. You fear that you have done yourself some unknown damage.</span> <span class="text">Take 1 horror.</span></div>'
shriveling[shriveling.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">Your enemy staggers around the room in agony.</span> <span class="text">Deal 5 damage and you may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Blood streams from your eyes and your vision grows blurry.</span> <span class="text">Take 1 damage. You lose the ability to cast Shriveling.</span></div>'

bind[bind.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">You execute the spell adeptly and are able to cast it without breaking your stride.</span> <span class="text">The monster is stunned. You may move 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">At the last moment, your enemy twists its body, evading the magical containment.</span> <span class="text">The keeper may move the monster 1 space.</span></div>'
bind[bind.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">The perfectly formed binding takes hold and starts to crush the monster with unseen viciousness.</span> <span class="text">The monster takes 2 damage and is stunned.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">A mispronunciation causes the spell to backfire. You feel the force of a giant sledgehammer knock you to the floor.</span> <span class="text">Take 1 damage and 1 horror.</span></div>'
bind[bind.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">Arcane energies surge through your body. The rush of power is both frightening and intoxicating.</span> <span class="text">All monsters in this room are stunned. Take 1 horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The room grows bitterly cold and you are surrounded by thick black smoke.</span> <span class="text">Take 1 horror. Then place a darkness token in this room.</span></div>'
bind[bind.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">Mystical forces twist their way around the creature\'s legs. The creature screams as the binding takes hold.</span> <span class="text">The monster is dealt 1 damage and is stunned.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">As the spell starts to congeal, the creature violently shakes, ripping its way out of the unseen shackles.</span> <span class="text">Take 1 horror.</span></div>'
bind[bind.length] = '<div><span class="passFail">Pass:</span> <span class="flavour">The air fills with electricity as unseen forces clamp down on the creature.</span> <span class="text">The monster is stunned.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">In a moment of panic, you completely forget how to cast the spell.</span> <span class="text">You lose the ability to cast Bind Monster.</span></div>'

/*
 *	Events
 */

var fallName = new Array( "The Clock Strikes 10", "The Clock Strikes 11", "The Clock Strikes 12", "The Clock Strikes 1", "The Clock Strikes 2" );
var tiesName = new Array( "A Bargain", "Another Servant", "A Mermoy", "The Plot Thickens", "Sunrise" );
var classroomName = new Array( "Lights Out", "Out of Order", "You're Not Alone", "Bad to Worse", "Curiosity Kills" );
var sanctumName = new Array( "A Late Arrival", "Dark Powers", "Urgency", "The Witching Hour", "You're Too Late" );
var greenName = new Array( "The Frozen Visitor", "A Touch of Madness", "The Devoted Servant", "The Horrific Vision", "You've Doomed Us All" );

var fallTime = [3, 4, 3, 3, 3];
var tiesTime = [2, 2, 5, 5, 5];
var classroomTime = [3, 3, 3, 5, 6];
var sanctumTime = [4, 4, 4, 4, 4];
var greenTime = [4, 5, 5, 5, 6];

fall[fall.length] = '<div class="title">Clock Strikes 10</div><div class="carbon">The Fall of House Lynch</div><div class="title">1</div><div class="text">If Clue 3 has not been found, each investigator teakes 1 horror. Otherwise, resolve 1 of the following:</div><hr/><div><span class="passFail">3A:</span> <span class="flavour">A fiery figure bolts down the hallway towards the bedroom.</span> <span class="text">Place a zombie in Hallway 2 with a fire token on him. When he is removed from play, place the fire token in his room.</span></div><hr/><div><span class="passFail">3B:</span> <span class="flavour">The skinless remains of a man throws open the door of the laboratory.</span> <span class="text">Place a zombie in the foyer. Each investigator then takes 1 horror.</span></div>'
fall[fall.length] = '<div class="title">Clock Strikes 11</div><div class="carbon">The Fall of House Lynch</div><div class="title">2</div><div class="text">If Clue 2 has not been found, each investigator teakes 1 horror. Otherwise, resolve 1 of the following:</div><hr/><div><span class="passFail">2A:</span> <span class="flavour">A madman picks up his axe and runs down the hall..</span> <span class="text">The keeper may move a maniac up to 2 spaces.</span></div><hr/><div><span class="passFail">2B:</span> <span class="flavour">The lights momentarily go out as an explosion of gunfire echoes down the hall.</span> <span class="text">Each investigator in a bedroom space is dealt 2 damage.</span></div>'
fall[fall.length] = '<div class="title">Clock Strikes 12</div><div class="carbon">The Fall of House Lynch</div><div class="title">3</div><div><span class="flavour">A living corpse rises up from its resting place. Judging from the pictures you\'ve seen, the corpse is undoubtedly Edith Lynch, albeit dead for weeks.</span> <span class="text">The keeper places 1 zombie in the room chosen for setup question number 2.</span></div>'
fall[fall.length] = '<div class="title">Clock Strikes 1</div><div class="carbon">The Fall of House Lynch</div><div class="title">4</div><div class="passFail">Reveal Objective.</div><hr/><div><span class="passFail">1A:</span> <span class="flavour">The ground shakes violently.</span> <span class="text">Place 1 time token on the next Event card.</span></div><hr/><div><span class="passFail">1B:</span> <span class="flavour">The old house groans.</span> <span class="text">Discard all Lock cards.</span></div><hr/><div><span class="passFail">1C:</span> <span class="flavour">The front door locks with a loud click.</span> <span class="text">In order to escape, investigators must solve Lock Puzzle #6B.</span></div>'
fall[fall.length] = '<div class="title">Clock Strikes 2</div><div class="carbon">The Fall of House Lynch</div><div class="title">5</div><div class="flavour">As the clock strikes 2 the ground begins to shake. Something ancient and deep beneath the house rapidly pulls the foundation down into the ground. The answers no longer matter as investigators and monsters struggle for their lives.</div><div><span class="passFail">1A:</span> <span class="text">The keeper wins the game.</span></div><div><span class="passFail">1B:</span> <span class="text">The investigators win the game.</span></div><div><span class="passFail">1A:</span> <span class="text">All players lose the game.</span></div>'

ties[ties.length] = '<div class="title">A Bargain</div><div class="carbon">Blood Ties</div><div class="title">1</div><div><span class="flavour">An alien voice cuts through the air. "Hello, preccciouzz one. Your uncle and I had a bargain, a pact youz see. Will you abide it?"</span> <span class="text">The blood relative must choose 1 of the following:</span></div><hr/><div><span class="text">Take 1 horror. Then gain the ability to cast Soul Pact or Blood Pact.</span> <span class="flavour">"I give you a glimmer of his great power!"</span></div><hr/><div><span class="text">Place a mi-go in your space.</span> <span class="flavour">"No, no, nooo. We must finish our workz!"</span></div>'
ties[ties.length] = '<div class="title">Another Servant</div><div class="carbon">Blood Ties</div><div class="title">2</div><div><span class="flavour">A faint buzzing sound cuts through the clear air coming from the shed. It seems like another one of Uncle Artie\'s acquaintances has come to visit.</span> <span class="text">Place a mi-go in the Storage Shed.</span></div>'
ties[ties.length] = '<div class="title">A Memory</div><div class="carbon">Blood Ties</div><div class="title">3</div><div><span class="flavour">You suddenly remember a Latin phrase your uncle taught you as a child. Translation: "I was what you are, and what I am you shall be."</span> <span class="text">The blood relative may have his investigator repead this to resolve the below effect. He may <b>not</b> know the result before chosing.</span></div><hr/><div><span class="passFail">5A:</span> <span class="flavour">Fire bursts out of the ground!</span> <span class="text">Place a fire token in the Graveyard.</span></div><hr/><div><span class="passFail">5B:</span> <span class="flavour">The earth groans as a rotted corpse rises from its grave.</span> <span class="text">Place a zombie in the Graveyard.</span></div>'
ties[ties.length] = '<div class="title">The Plot Thickens</div><div class="carbon">Blood Ties</div><div class="title">4</div><div class="passFail">Reveal Objective.</div><hr/><span class="passFail">1A:</span> <span class="flavour">You made the wrong bargain.</span> <span class="text">If the blood relative has the ability to cast Soul Pact or Blood Pact, place 1 sample token on the altar.</span></div><hr/><span class="passFail">1B:</span> <span class="flavour">The wind spreads the fire.</span> <span class="text">The keeper may place a fire marker in a room adjacent to a room on fire.</span></div><hr/><div><span class="passFail">1C:</span> <span class="flavour">Your heart stops for a second.</span> <span class="text">Deal 1 damage to the blood relative.</span></div>'
ties[ties.length] = '<div class="title">Sunrise</div><div class="carbon">Blood Ties</div><div class="title">5</div><div class="text">All players lose the game.</div><hr/><span class="passFail">1A:</span> <span class="flavour">Artimus foolishly attempts the ritual without the proper blood offering. His heart, and that of his blood relative, both explode.</span></div><hr/><span class="passFail">1B:</span> <span class="flavour">The sun finally rises and the zombies disappear. Twelve hours later, the same nightmare returns.</span></div><hr/><div><span class="passFail">1C:</span> <span class="flavour">You live the rest of your life penniless, with the curse of bad luck following you to an early grave.</span></div>'

classroom[classroom.length] = '<div class="title">Lights Out</div><div class="carbon">Classroom Curses</div><div class="title">1</div><div><span class="flavour">The lights begin to flicker and dim. From the switches and fixtures throughout the building, sparks fly and loud popping noises are heard. A distinct odor of ozone and burnt wiring fills the air, as some of the rooms are plunged into darkness.</span> <span class="text">The keeper chooses 2 rooms and places a darkness token in each of them. Each investigator in either of those rooms must test Dexterity.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The sparks sear your skin.</span> <span class="text">Take 1 damage.</span></div>'
classroom[classroom.length] = '<div class="title">Out of Order</div><div class="carbon">Classroom Curses</div><div class="title">2</div><div><span class="passFail">4A:</span> <span class="flavour">Fire shoots out from the furnace, engulfing the room in flames.</span> <span class="text">Place a fire token in the Furnace Room.</span></div><hr/><div><span class="passFail">4B:</span> <span class="flavour">The temperature in the freezer plummets at an alarming rate.</span> <span class="text">Each investigator in the Freezer is dealt 2 damage and loses 1 skill point.</span></div>'
classroom[classroom.length] = '<div class="title">Not Alone</div><div class="carbon">Classroom Curses</div><div class="title">3</div><div><span class="passFail">1A:</span> <span class="flavour">Buzzing voices echo through the heating ducts.</span> <span class="text">Place 1 mi-go in any room with a vent.</span></div><hr/><div><span class="passFail">1B:</span> <span class="flavour">Voices can be heard in the Gallery. "You\'re too worried. We didn\'t summon anything."</span> <span class="text">Place 2 witches in the Gallery.</span></div><hr/><div><span class="passFail">1C:</span> <span class="flavour">Helena Detaigne\'s voice calls from the Library. "Welcome, fools!"</span> <span class="text">The keeper places Helena in the Library. Helena is a witch with +4 health per investigator.</span></div>'
classroom[classroom.length] = '<div class="title">Bad to Worse</div><div class="carbon">Classroom Curses</div><div class="title">4</div><div class="passFail">Reveal Objective.</div><hr/><div><span class="passFail">1A, 1C:</span> <span class="flavour">More of the strange creatures crawl out from the duct.</span> <span class="text">If no mi-go are on the board, the keeper places 1 mi-go in each room with a vent. If only 1 mi-go is on the board, the keeper places 1 mi-go in any room with a vent.</span></div><hr/><div><span class="passFail">1B:</span> <span class="flavour">The two students\' arecane experiements are having side effects.</span> <span class="text">The keeper places a hound of tindalos in the Attic Storage. This houd of tindalos has +4 health per investigator.</span></div>'
classroom[classroom.length] = '<div class="title">Curiosity Kills</div><div class="carbon">Classroom Curses</div><div class="title">5</div><div><span class="passFail">1A:</span> <span class="flavour">The mi-go are everywhere!</span> <span class="text">The keeper wins the game.</span></div><hr/><div><span class="passFail">1B:</span> <span class="flavour">Fog begins pouring out of the angles of every room. More of the strange creatures have arrived.</span> <span class="text">All players lose the game.</span></div><hr/><div><span class="passFail">1C:</span> <span class="flavour">Despite whatever bargain was struck between Helena and the mi-go, swarms of the beasts overrun her as well as the investigators.</span> <span class="text">All players lose the game.</span></div>'

sanctum[sanctum.length] = '<div class="title">A Late Arrival</div><div class="carbon">The Inner Sanctum</div><div class="title">1</div><div><span class="flavour">The door to the chapel opens, letting driving wind and rain into the room. A robed figure enters, carrying an unconscious woman over his shoulder.</span> <span class="text">The keeper places a cult leader in the chapel. If an investigator kills this monster, he gains 1 skill point and the "Cult Robes" exploration card.</span></div>'
sanctum[sanctum.length] = '<div class="title">Dark Powers</div><div class="carbon">Dark Powers</div><div class="title">2</div><div><span class="flavour">Deep within the monastery, an ancient ceremony begins. Blood is spilled and a dark power closes its grasp on your soul.</span> <span class="text">The keeper gains 1 threat for each cultist and cult leader on the game board.</span></div>'
sanctum[sanctum.length] = '<div class="title">Urgency</div><div class="carbon">The Inner Sanctum</div><div class="title">3</div><div><span class="flavour">A sense of urgency fills the monastery. Time is running out, and the burning feeling is almost tangible.</span> <span class="text">The keeper may move each cultist 1 space. Each investigator may then move 1 space.</span></div>'
sanctum[sanctum.length] = '<div class="title">The Witching Hour</div><div class="carbon">The Inner Sanctum</div><div class="title">4</div><div><span class="passFail">1A:</span> <span class="flavour">You cover your ears and pray for the strange voices to get out of your head.</span> <span class="passFail">Reveal Objective.</span> <span class="text">The keeper chooses an investigator to take 1 horror.</span></div><hr/><div><span class="passFail">1B:</span> <span class="flavour">The ritual is about to begin!</span> <span class="text">The keeper may move each cultist 1 space.</span></div><hr/><div><span class="passFail">1C:</span> <span class="flavour">A hulking cultist guards the front door with a large knife in hand.</span> <span class="passFail">Reveal Objective.</span> <span class="text">The keeper places a cult leader in the chapel.</span></div>'
sanctum[sanctum.length] = '<div class="title">Too Late...</div><div class="carbon">The Inner Sanctum</div><div class="title">5</div><div><span class="flavour">The witching hour comes and goes without the ritual taking effect. Angry cultists start to flood into your room, looking for a target for their rage. They quickly form a circle around you and, in a primal fury, begin to tear you apart.</span> <span class="text">If Clue 1B has been found, the investigators win the game. Otherwise, all players lose the game.</span></div>'

green[green.length] = '<div class="title">Frozen Visitor</div><div class="carbon">Green-eyed Boy</div><div class="title">1</div><div class="flavour">The door flies open and a hysterical man enters the room. He wears a thick winter jacket and icicles cover his salt and pepper beard. He runs to you and grabs the collar of your shirt. "Oh god," he weeps, "it is unspeakably horrible." His legs give way and he collapses to the floor. "I should have listened. Damn curiosity, damn it to hell." He looks up at you. "Please save yourself, save everyone. Whatever you do, do not open the freezer&mdash;" His eyes close for the last time.</div>'
green[green.length] = '<div class="title">Touch of Madness</div><div class="carbon">Green-eyed Boy</div><div class="title">2</div><div><span class="passFail">6A:</span> <span class="flavour">A door slams open and the boy runs frantically through. A madman chases him, axe high over his head.</span> <span class="text">The keeper places 1 maniac in any investigator\'s room.</span></div><hr/><div><span class="passFail">6B:</span> <span class="flavour">You hear murmuring voices, growing louder and louder. You grab your head and yell, "SHUT UP!" Silence. The boy appears around the corner with a finger on his lips. "Shhh."</span> <span class="text">Each investigator takes 1 horror.</span></div>'
green[green.length] = '<div class="title">Devoted Servant</div><div class="carbon">Green-eyed Boy</div><div class="title">3</div><div><span class="flavour">The door behind you suddenly opens. You spin around, weapon in hadn, to find the butler, now in a full robe. "Are you surprised to see me?" He grins a devious smile. "I am a devoted servant and have work to complete. I will not let you jeopardize my mission."</span> <span class="text">The keeper places a cult leader in any investigator\'s room.</span></div>'
green[green.length] = '<div class="title">Horrific Vision</div><div class="carbon">Green-eyed Boy</div><div class="title">4</div><div class="passFail">Reveal Objective.</div><hr/><div><span class="passFail">1A:</span> <span class="flavour">You hear a woman\'s voice. "He is MY boy! MY probperty!"</span> <span class="text">Place 1 time token on the Event deck.</span></div><hr/><div><span class="passFail">1B:</span> <span class="flavour">You see the boy\'s face in your mind, horrified and covered in ice.</span> <span class="text">The keeper draws 3 Mythos cards.</span></div><hr/><div><span class="passFail">1C:</span> <span class="flavour">You glance out the window just in time to see a boy fall past.</span> <span class="text">The keeper choses an investigator to take 1 horror.</span></div>'
green[green.length] = '<div class="title">Doomed Us All</div><div class="carbon">Green-eyed Boy</div><div class="title">5</div><div><span class="passFail">1A:</span> <span class="flavour">Every door to the mansion slams shut, and every light goes out.</span> <span class="text">The keeper wins the game.</span></div><hr/><div><span class="passFail">1B:</span> <span class="flavour">You suddenly find yourself in the middle of a frosty wasteland. The mansion, the only entrance to your world, has vanished forever.</span> <span class="text">All players lose the game.</span></div><hr/><div><span class="passFail">1C:</span> <span class="flavour">Rather than live with the guilt, you take your own life.</span> <span class="text">All players lose the game.</span></div>'

/*
 *	Humanoid Attacks (Investigator)
 */

humanoidUnarmed[humanoidUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You make a sweeping kick aimed at your enemy\'s legs.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your opponent falls to the floor, grabbing its knee.</span> <span class="text">Deal 1 damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You feel as if you have kicked a stone wall.</span> <span class="text">Take 1 damage.</span></div>';
humanoidUnarmed[humanoidUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">In a panicked frenzy, you attack your enemy with your bare hands.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You rake at its eyes with your fingernails.</span> <span class="text">Deal 2 damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It laughs as blood drips down its face.</span> <span class="text">Take 1 horror.</span></div>';
humanoidUnarmed[humanoidUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You grapple your opponent and grab its head.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">Its neck twist with a sickening snap.</span> <span class="text">Deal damage equal to half your strength (rounded up).</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It evades your grasp.</span> <span class="text">No effect.</span></div>';
humanoidUnarmed[humanoidUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You yell out in defiance and charge your enemy.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You kick it in the side of the head, knocking it heavily to the ground.</span> <span class="text">Deal 3 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You overshoot it and land hard.</span> <span class="text">You are stunned.</span></div>';
humanoidUnarmed[humanoidUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You aim a right cross at your enemy\'s jaw.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your fist lands solidy across its face.</span> <span class="text">Deal 1 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You put too much strength behind the punch and throw yourself off balance.</span> <span class="text">No effect.</span></div>';

humanoidSharp[humanoidSharp.length] = '<div class="title">Sharp Melee Weapon</div><div><span class="flavour">You swing the weapon at your enemy\'s wrist.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You cleanly slice off one of its hands.</span> <span class="text">Deal weapon damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It spins away from you.</span> <span class="text">No effect.</span></div>';
humanoidSharp[humanoidSharp.length] = '<div class="title">Sharp Melee Weapon</div><div><span class="flavour">You swing back your weapon and then go in for the kill.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your weapon cleanly slices an artery in a spray of blood.</span> <span class="text">Deal weapon damage +2 and take 1 horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It blocks your attack with its arm. Deal 1 damage.</span> <span class="text"></span></div>';

humanoidBlunt[humanoidBlunt.length] = '<div class="title">Blunt Melee Weapon</div><div><span class="flavour">You prepare to beat your enemy senseless.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You knowck your enemy unconscious.</span> <span class="text">Deal weapon damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your frail swings have little effect.</span> <span class="text">Deal 1 damage.</span></div>';
humanoidBlunt[humanoidBlunt.length] = '<div class="title">Blunt Melee Weapon</div><div><span class="flavour">You raise your weapon in the air and grit your teeth.</span></div><div class="test">Test Strength -1.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your weapon comes down on its head with a sickly thump.</span> <span class="text">Deal weapon damage +2 and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your assault stalls it momentarily.</span> <span class="text">Stun the monster.</span></div>';

humanoidMelee[humanoidMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You swing low, aiming for your opponent\'s knees.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your enemy drops to the floor, crippled by your attack.</span> <span class="text">Deal weapon damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your enemy hops out of the path of your attack.</span> <span class="text">No effect.</span></div>';
humanoidMelee[humanoidMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You take a wide swing at your assailant, striking him across the chest.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">It groans and lurches forward in pain.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It catches your weapon and pulls it away from you.</span> <span class="text">Drop this weapon.</span></div>';
humanoidMelee[humanoidMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You receive a burst of courage and charge the monster.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your weapon sinks deep into its skull.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It ducks at the last moment, and you swing right over it.</span> <span class="text">No effect.</span></div>';
humanoidMelee[humanoidMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You run forward and swing for your enemy\'s head.</span></div><div class="test">Test Strength -1.</div><div><span class="passFail">Pass:</span> <span class="flavour">You scream as your weapon rips its head right off its body.</span> <span class="text">Deal weapon damage +4.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It evades your attack and grabs your leg.</span> <span class="text">Take 1 damage.</span></div>';
humanoidMelee[humanoidMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">In a moment of panic, you throw your weapon at your assailant.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The weapon strikes it right between the eyes.</span> <span class="text">Deal weapon damage +2 and drop this weapon.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The weapon soars over the head of your intended target.</span> <span class="text">Drop this weapon.</span></div>';
humanoidMelee[humanoidMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You quickly jab your weapon into the chest of your enemy.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your assailant backs away, startled by your attack.</span> <span class="text">Deal 2 damage. You may then move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your feeble attack leaves you vulnerable.</span> <span class="text">Take 1 damage.</span></div>';

humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">As you raise your firearm, your nervous hands fumble the weapon.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">The moment passes and you fire with confidence.</span> <span class="text">Deal weapon damage -1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The gun hits the ground before you can fire.</span> <span class="text">Drop this weapon.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You aim for your enemy\'s heart.</span></div><div class="test">Test Marksmanship -1.</div><div><span class="passFail">Pass:</span> <span class="flavour">Its chest explodes in a spray of gore.</span> <span class="text">Deal weapon damage +3.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your shot goes high and grazes its shoulder</span> <span class="text">Deal 1 damage.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">Right before you pull the trigger, your opponent screams and charges you.</span></div><div class="test">Test Willpower.</div><div><span class="passFail">Pass:</span> <span class="flavour">You coolly fire into its chest.</span> <span class="text">Deal weapon damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It startles you and the shot goes wide.</span> <span class="text">No effect.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">Without breaking your stride, you fire and continue walking.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your shot connects, and your target stumbles backward.</span> <span class="text">Deal 2 damage and you may move 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You trip over your feet and the shot misses.</span> <span class="text">Take 1 damage.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You quickly draw your weapon and fire.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your instincts are flawless.</span> <span class="text">Deal weapon damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The shot doesn\'t even come close to hitting your enemy.</span> <span class="text">No effect.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You hear the gun go off, but in your shock, you aren\'t even aware that you fired it.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your instincts did not fail.</span> <span class="text">Deal weapon damage -1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You fired into the ground.</span> <span class="text">No effect.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">On pure instinct and adrenaline, you fire instantly.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">He screams as a bullet is buried in his leg.</span> <span class="text">Deal weapon damage -1 and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The gunpowder burns your skin.</span> <span class="text">Take 1 damage and drop this weapon.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You catch the monster in your sights.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The shot punctures its lung.</span> <span class="text">Deal weapon damage +2.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your shot grazes its shoulder, alerting it to your presence.</span> <span class="text">Deal 1 damage. The keeper may then move any monster up to 2 spaces.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You carefully line up your shot and fire.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The top half of its head is completely blown off.</span> <span class="text">Deal weapon damage +2.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your shot goes wide, and the flash of the gun blinds you.</span> <span class="text">You are stunned.</span></div>';
humanoidRanged[humanoidRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You charge the monster, gun blazing.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The shot lifts its body into the air, and it flies across the room.</span> <span class="text">Deal weapon damage and you may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Somehow every bullet misses, and it lunges at you.</span> <span class="text">If the monster is in your space, take 1 damage.</span></div>';

humanoidSharp = humanoidSharp.concat( humanoidMelee );
humanoidBlunt = humanoidBlunt.concat( humanoidMelee );

/*
 *	Humanoid Attacks (Monster)
 */

humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The monster goes for your throat.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You barely avoid its grasp.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Its fingers close around your windpipe.</span> <span class="text">Take 2 damage and you are stunned.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">It swings both its fists down at your head.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">It barely misses you.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Its fists come down in a powerful blow.</span> <span class="text">The monster damages you.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">Your enemy walks towards you, with an insane grin on its face.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You push it to the floor.</span> <span class="text">Deal 1 damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It cuts into your flesh with a long blade.</span> <span class="text">The monster damages you.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">With no sense of self-preservation, your enemy lashes out at you.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You manage to injure it and avoid its attack.</span> <span class="text">Deal 1 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You wound your assailant, but suffer greatly for it.</span> <span class="text">Deal 1 damage and take 2 damage.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The monster charges you, screaming gibberish.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You grunt with effort and shove it away.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It overpowers you and stars gnawing at your face.</span> <span class="text">Take 1 horror and the monster damages you.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">Your enemy dives at you.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You sidestep its attack.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You are tackled to the floor.</span> <span class="text">Take 1 damage and you are stunned.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">Your assailant attempts to sink its teeth into your shoulder.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You squirm out of its grasp.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It bites you and pain shoots through your arm and shoulder.</span> <span class="text">The monster damages you.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The enmy tries to pin you to the floor.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You elbow your opponent in the lungs.</span> <span class="text">Stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You are overpowerd.</span> <span class="text">The monster damages you.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The savage enemy lunges at your face.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You dive to the floor, barely avoiding its attack.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It grabs your face and scratches at your eyes.</span> <span class="text">Take 2 damage and you are stunned.</span></div>';
humanoidMonster[humanoidMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">Your enemy moves with alarming speed, anticipating your every move.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You prove too unpredictable to be struck.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">How can it possibly know what you\'re thinking?</span> <span class="text">The monster damages you.</span></div>';

humanoidHiding[humanoidHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">You hear the slow, careful footsteps of your enemy.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">Wherever the enmy looks, you aren\'t there.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You stumble trying to avoid its notice.</span> <span class="text">You are dealt 1 damage and are no longer hiding.</span></div>';
humanoidHiding[humanoidHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">You hear your enemy searching through random objects.</span></div><div class="test">Test luck.</div><div><span class="passFail">Pass:</span> <span class="flavour">In its haste, it doesn\'t find you and moves on.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You are disovered.</span> <span class="text">You are no longer hiding.</span></div>';
humanoidHiding[humanoidHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">The enmy makes a visual scan of the area.</span></div><div class="test">Make an evade test.</div><div><span class="passFail">Pass:</span> <span class="flavour">It sees nothing and continues on.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It spies a ripped piece of clothing you hastily left behind.</span> <span class="text">You are no longer hiding.</span></div>';
humanoidHiding[humanoidHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">You set a diversion, and hide in the shadows.</span></div><div class="test">Test Intellect +1.</div><div><span class="passFail">Pass:</span> <span class="flavour">The monster takes the bait.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your ruse was flawed.</span> <span class="text">You are no longer hiding. The monster then attacks you again.</span></div>';
humanoidHiding[humanoidHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">You hear your enemy stop in the middle of the room, listening for you.</span></div><div class="test">Test Willpower.</div><div><span class="passFail">Pass:</span> <span class="flavour">You remain perfectly still until the enemy moves on.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You can\'t stop shaking.</span> <span class="text">You are stunned and no longer hiding.</span></div>';

humanoidBarrier[humanoidBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">Your enemy throws its entire weight against the door, trying to smash its way in.</span></div><div class="test">Test the monster\'s damage value +1.</div><div><span class="passFail">Pass:</span> <span class="text">The barrier is destroyed.</span></div><div><span class="passFail">Fail:</span> <span class="text">No effect.</span></div>';
humanoidBarrier[humanoidBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The enemy pounds on the door with its fists.</span></div><div class="text">If the monster\'s damage value is 2 or more, the barrier is destroyed.</div>';
humanoidBarrier[humanoidBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The barrier slides across the floor and ultimately falls over as the door is pushed open.</span></div><div class="text">The keeper may move the barrier marker off the door and back into its starting space.</div>';
humanoidBarrier[humanoidBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The enemy charges the door and bounces right off.</span></div><div class="text">The monster is dealt 1 damage.</div>';
humanoidBarrier[humanoidBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">Your enemy bursts through the door, splintered wood embedding itself into the monster\'s flesh.</span></div><div class="text">The barrier is destroyed. The monster is then dealt 2 damage.</div>';

/*
 *	Beast Attacks (Investigator)
 */

beastUnarmed[beastUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You grab the creature by the jaws and attempt to pry them apart.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You feel a snap and the monster howls.</span> <span class="text">Deal 2 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It\'s too strong and its jaws snap shut.</span> <span class="text">Take 1 damage.</span></div>';
beastUnarmed[beastUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You confront the monster, meeting its gaze with your own.</span></div><div class="test">Test Willpower.</div><div><span class="passFail">Pass:</span> <span class="flavour">The monster hesitates in the face of your steely courage.</span> <span class="text">Stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It knows you are afraid.</span> <span class="text">Take 1 horror.</span></div>';
beastUnarmed[beastUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You grab the monster and begin punching it repeatedly.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your sudden pummeling takes the beast by surprise.</span> <span class="text">Deal 1 damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your fists are cut on the monster\'s thick hide.</span> <span class="text">Take 1 damage.</span></div>';
beastUnarmed[beastUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">Desperate to fight, you sink your teeth into the monster\'s flesh and bite hard.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">The creature\'s blood begins to fill your mouth.</span> <span class="text">Deal 2 damage and take 1 horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You don\'t seem to be hurting it, but the taste in your mouth is respulsive.</span> <span class="text">Take 1 horror.</span></div>';

beastSharp[beastSharp.length] = '<div class="title">Sharp Melee Weapon</div><div><span class="flavour">You aim your attack at the creature\'s face.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You embed your weapon into one of its eyes.</span> <span class="text">Deal weapon damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Its neck bends at an impossible angle, allowing it to avoid your attack.</span> <span class="text">No effect.</span></div>';
beastSharp[beastSharp.length] = '<div class="title">Sharp Melee Weapon</div><div><span class="flavour">With all your strength, you plunge the blade into the beast\'s side.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your weapon sinks into the leathery flesh, covering your arm in a dark liquid.</span> <span class="text">Deal weapon damage and take 1 horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The creature\'s thick hide seems impenetrable.</span> <span class="text">No effect.</span></div>';

beastBlunt[beastBlunt.length] = '<div class="title">Blunt Melee Weapon</div><div><span class="flavour">You put your pack into your swing.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">The force of your weapon comes down on its torso.</span> <span class="text">Deal weapon damage -1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your arms sting as if you had hit a brick wall.</span> <span class="text">Drop this weapon.</span></div>';
beastBlunt[beastBlunt.length] = '<div class="title">Blunt Melee Weapon</div><div><span class="flavour">You pull out your weapon and go in for the kill.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your weapon comes down on its back with a sickening snap.</span> <span class="text">Deal weapon damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your assault has little effect on the creature.</span> <span class="text">Deal 1 damage.</span></div>';

beastMelee[beastMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You run forward and swing for your enemy\'s head.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">With a grunt of effort, your weapon caves in part of the monster\'s head.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">With frightening speed, the creature squirms out of the way.</span> <span class="text">No effect.</span></div>';
beastMelee[beastMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You strike the back of the best\'s head with all of your might.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your weapon breaks across the creature\'s skull.</span> <span class="text">Deal weapon damage +3 and discard this weapon.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You manage to strikje a glancing blow.</span> <span class="text">Deal 1 damage.</span></div>';
beastMelee[beastMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You attempt a strategic feint before swinging at the monster.</span></div><div class="test">Test Intellect.</div><div><span class="passFail">Pass:</span> <span class="flavour">It fell for your ruse and was completely vulnerable to your attack.</span> <span class="text">Deal weapon damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It knew what you were doing.</span> <span class="text">Take 2 damage.</span></div>';
beastMelee[beastMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You swing your weapon, intent on crippling the monster.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You hear a crack as your weapon strikes.</span> <span class="text">Deal 2 damage and the monster is stunned.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It quickly moves its leg out of the way.</span> <span class="text">No effect.</span></div>';

beastRanged[beastRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You patiently wait for the right moment and then take your shot.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The monster wails as your shot rips into one of its eyes.</span> <span class="text">Deal weapon damage +2.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You waited too long.</span> <span class="text">If the monster is in the same space as you, take 2 damage.</span></div>';
beastRanged[beastRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You empty your entire clip into the horrible creature.</span></div><div class="test">Test Luck.</div><div><span class="passFail">Pass:</span> <span class="flavour">Most of the bullets hit home.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your shots throw you off balance, butinjure the enemy.</span> <span class="text">Deal weapon damage -1. You are stunned.</span></div>';
beastRanged[beastRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You repeatedly fire at the monster\'s head with professional skill.</span></div><div class="test">Test Marksmanship +1.</div><div><span class="passFail">Pass:</span> <span class="flavour">It shrieks as the room is painted with its odd blood.</span> <span class="text">Deal weapon damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It bolts out of the way with impossible speed.</span> <span class="text">No effect.</span></div>';
beastRanged[beastRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You shout to gain the beast\'s attention and then shoot.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your bullet hits!</span> <span class="text">Deal weapon damage and the monster is stunned.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The monster is enraged.</span> <span class="text">If the monster is in the same space as you, take 1 damage.</span></div>';
beastRanged[beastRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You fire repeatedly as the creature races around the room.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">It\'s not fast enough.</span> <span class="text">Deal weapon damage -1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The monster is only grazed by your shots.</span> <span class="text">Deal 1 damage.</span></div>';
beastRanged[beastRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You make a guess as to where the creature\'s heart lies.</span></div><div class="test">Test Intellect.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your bullet rips into the creature and it howls in pain.</span> <span class="text">Deal weapon damage +2.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The creature is unfazed by your rain of bullets.</span> <span class="text">No effect.</span></div>';
beastRanged[beastRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">With blazing speed, you aim and fire at the approaching creature.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The beast never knew what hit it.</span> <span class="text">Deal weapon damage +1 and the monster is stunned.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You tried to move too quickly.</span> <span class="text">Drop this weapon.</span></div>';
beastRanged[beastRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">The monster pauses upon seeing you. You take the opportunity to open fire.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The bullet lodges in its hide, obviously causing it pain.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your shot seems to bounce right off it.</span> <span class="text">No effect.</span></div>';

beastSharp = beastSharp.concat( beastMelee );
beastBlunt = beastBlunt.concat( beastMelee );

/*
 *	Beast Attacks (Monster)
 */

beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The bloodthirsty enemy lunges at your throat.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You dive to the floor, barely doging its attack.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Its teeth sink into the soft flesh of your neck.</span> <span class="text">Take 3 damage and you are stunned.</span></div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The creature stands to its full height and leaps forward.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You dodge out of the way.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You are overpowered.</span> <span class="text">Take 2 damage and you are stunned.</span></div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The monster pushes against you, trying to pin you to the floor.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You push the creature away.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You\'re on the ground, unable to move or breathe.</span> <span class="text">Take 2 damage and you are stunned.</span></div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The beast reaches forward and slashes at you with one of its appendages.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You back away from the monster\'s attack in time.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You watch as your blood spills to the floor.</span> <span class="text">Take 2 damage and 1 horror.</span></div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The monster kicks you square in the chest.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You brace yourself and absorb the impact.</span> <span class="text">Take 1 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The force of the kick throws you violently backward.</span> <span class="text">The monster damages you and the keeper may move you 1 space.</span></div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The monster lurches forward, head first, trying to knock you over.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You drive the creature into the ground.</span> <span class="text">Deal 1 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You are knocked off your feet by the monster\'s charge.</span> <span class="text">The monster damages you and you are stunned.</span></div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The monster roars, and bites at you.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You barely avoid its maw.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You fall back as it takes a bloody chunk out of your arm.</span> <span class="text">Take 2 damage. The keeper then chooses a weapon for you to drop in this room.</span></div>';
beastMonster[beastMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The creature lunges at your arm.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You free yourself from the creature\'s grasp.</span> <span class="text">Take 1 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It latches its jaws onto your hand.</span> <span class="text">The monster damages you. The keeper then chooses a weapon for you to drop in this room.</span></div>';

beastHiding[beastHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">The monster pauses and sniffs the air.</span></div><div class="test">Test Willpower.</div><div><span class="passFail">Pass:</span> <span class="flavour">You remain calm and it slowly wanders off.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You begin sweating profusely, and it easily detects your scent.</span> <span class="text">You are no longer hiding.</span></div>';
beastHiding[beastHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">The monster thrashes about, tossing things into the air.</span></div><div class="test">Test Willpower.</div><div><span class="passFail">Pass:</span> <span class="flavour">You are funfazed.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The noise overwhelms you and you cry out.</span> <span class="text">You are no longer hiding. The monster then attacks you again.</span></div>';
beastHiding[beastHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">You think your hiding spot is clever enough to evade detection.</span></div><div class="test">Test Intellect.</div><div><span class="passFail">Pass:</span> <span class="flavour">The monster never had a clue where you were.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You\'re the one who was outsmarted.</span> <span class="text">You are stunned and no longer hiding.</span></div>';
beastHiding[beastHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">You hear the monster searching for a trace of you.</span></div><div class="test">Make an evade test.</div><div><span class="passFail">Pass:</span> <span class="flavour">You left no trace for the monster to find.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You were careless and now the monster has found you.</span> <span class="text">You are no longer hiding.</span></div>';

beastBarrier[beastBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The monster charges toward the door, lowering its head to charge through.</span></div><div class="test">Test the monster\'s damage value +1.</div><div><span class="passFail">Pass:</span> <span class="text">The barrier is destroyed.</span></div><div><span class="passFail">Fail:</span> <span class="text">The monster is dealt 1 damage.</span></div>';
beastBarrier[beastBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The creature throws its entire weight into the door.</span></div><div class="test">Test the monster\'s health value.</div><div><span class="passFail">Pass:</span> <span class="text">The barrier is destroyed.</span></div><div><span class="passFail">Fail:</span> <span class="text">The monster is dealt 2 damage.</span></div>';
beastBarrier[beastBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The monster bursts through the door, barely noticing the splinters stuck in its hide.</span></div><div class="text">Deal 1 damage to the monster and the barrier is destroyed.</div>';
beastBarrier[beastBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The monster scratches fiercely at the blocked door.</span></div><div class="text">If the monster\'s damage value is 3 or more, the barrier is destroyed.</div>';

/*
 *	Eldritch Attacks (Investigator)
 */

eldritchUnarmed[eldritchUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You try to subdue the horrific thing by hammering it with your fists.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">The creature retreats away from you.</span> <span class="text">Deal 1 damage and you may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your hand breaks against its unnatural hide.</span> <span class="text">Take 1 damage.</span></div>';
eldritchUnarmed[eldritchUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You wrap its tentacle around your arm and pull with all your might.</span></div><div class="test">Test Strength -1.</div><div><span class="passFail">Pass:</span> <span class="flavour">With a horrible pop, you pull the tentacle off the abomination.</span> <span class="text">Deal 2 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The nightmarish thing throws you around the room.</span> <span class="text">Take 1 damage.</span></div>';
eldritchUnarmed[eldritchUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You beat the abomination with whatever items you can find.</span></div><div class="test">Test Luck +3.</div><div class="text">If you do not have any equipment cards, you automatically fail.</div><div><span class="passFail">Pass:</span> <span class="flavour">The item sticks deep into the creature\'s flesh.</span> <span class="text">Deal 2 damage and drop 1 equipment card.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It seems to laugh.</span> <span class="text">No effect.</span></div>';
eldritchUnarmed[eldritchUnarmed.length] = '<div class="title">No Weapon</div><div><span class="flavour">You punch your hand through its skin and search for something to squeeze.</span></div><div class="test">Test Willpower.</div><div><span class="passFail">Pass:</span> <span class="flavour">You dig your fingers into an alien organ and the creature shrieks.</span> <span class="text">Deal 1 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Its slimy insides burn your flesh.</span> <span class="text">Take 1 damage and 1 horror.</span></div>';

eldritchSharp[eldritchSharp.length] = '<div class="title">Sharp Melee Weapon</div><div><span class="flavour">You lunge, hoping to bury your blade in the abomination\'s squamous flesh.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">The blade punctures its body, and a foul ichor pours out.</span> <span class="text">Deal weapon damage +1 and take 1 horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your blade cannot pierce its skin.</span> <span class="text">Take 1 damage.</span></div>';
eldritchSharp[eldritchSharp.length] = '<div class="title">Sharp Melee Weapon</div><div><span class="flavour">A tentacle swings at your face, and you aim to dismember it.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">The tentacle is sliced off and sails across the room.</span> <span class="text">Deal weapon damage -1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It grabs your skull.</span> <span class="text">Take 1 damage.</span></div>';

eldritchBlunt[eldritchBlunt.length] = '<div class="title">Blunt Melee Weapon</div><div><span class="flavour">You jump and swing your weapon down on the horror.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">The full weight of you body and weapon leaves a gaping hole in the creature.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You muss and land hard on the floor.</span> <span class="text">You are stunned.</span></div>';
eldritchBlunt[eldritchBlunt.length] = '<div class="title">Blunt Melee Weapon</div><div><span class="flavour">You swing the weapon over your head and bring it down on top of the abomination.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your weapon crushes the creature with a sickening pop.</span> <span class="text">Deal weapon damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your assault stalls it momentarily.</span> <span class="text">Deal 1 damage.</span></div>';

eldritchMelee[eldritchMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">Tentacles surround you and you lash out with your weapon.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Each of your strikes seems to injur the abomination.</span> <span class="text">Deal weapon damage +2.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You exhaust yourself without accomplishing anything.</span> <span class="text">Take 1 horror.</span></div>';
eldritchMelee[eldritchMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You try to crush one of its slithering appendages.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your weapon flattens the tentacle into jelly.</span> <span class="text">Deal weapon damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your weapon sticks to the creature\'s skin and is pulled from your hands.</span> <span class="text">Drop this weapon.</span></div>';
eldritchMelee[eldritchMelee.length] = '<div class="title">Melee Weapon</div><div><span class="flavour">You strike the horrible thing repeatedly as fast as you can.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">The reapid-fire bludgeoning seems to wound the thing.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">In your haste, the weapon slips from your hands.</span> <span class="text">Drop this weapon.</span></div>';
eldritchMelee[eldritchMelee.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You scream as you fire at the advancing abomination.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your attack slows the best.</span> <span class="text">Deal weapon damage -1 and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It appears unfazed.</span> <span class="text">No effect.</span></div>';

eldritchRanged[eldritchRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You aim at a nearby lantern and fire.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The explosion sets the room ablaze, cooking the abomination.</span> <span class="text">Deal weapon damage. Then place a fire toekn in the room.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your bullets fly harmlessly into the ground.</span> <span class="text">No effect.</span></div>';
eldritchRanged[eldritchRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You stand unflinchingly, firing round after round at the abomination.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The horrible thing makes an unearthly noise as your bullets sink in.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The abomination does not seem affected.</span> <span class="text">Take 1 horror.</span></div>';
eldritchRanged[eldritchRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You aim towards its most vulnerable looking spot.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">You bury a bullet in what you believe is one of its eyes.</span> <span class="text">Deal weapon damage and stun the monster.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">It appears to be unstoppable!</span> <span class="text">Take 1 horror.</span></div>';
eldritchRanged[eldritchRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You remember reading about this creature\'s weaknesses in an ancient tome.</span></div><div class="test">Test Intellect.</div><div><span class="passFail">Pass:</span> <span class="flavour">Your memory serves you well. The creature shrieks as your hot lead tears into it.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The knowledge is stuck on the tip of your mind.</span> <span class="text">No effect.</span></div>';
eldritchRanged[eldritchRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">The monstrosity slithers towards you.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">You quickly fire at it, spraying the room with slime.</span> <span class="text">Deal weapon damage -1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your gun jams and refuses to fire.</span> <span class="text">Drop this weapon.</span></div>';
eldritchRanged[eldritchRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You close your eyes and fire blindly at the approaching abomination.</span></div><div class="test">Test Luck +1.</div><div><span class="passFail">Pass:</span> <span class="flavour">You open your eyes, and the horror seems visibly wounded.</span> <span class="text">Deal weapon damage +1.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You open your eyes, but the nightmare is still there.</span> <span class="text">Take 1 horror.</span></div>';
eldritchRanged[eldritchRanged.length] = '<div class="title">Ranged Weapon</div><div><span class="flavour">You shower the enemy with bullets.</span></div><div class="test">Test Marksmanship.</div><div><span class="passFail">Pass:</span> <span class="flavour">The creature is riddled with holes.</span> <span class="text">Deal weapon damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Your bullets bounce off its alien flesh, and you are hit by some ricochet.</span> <span class="text">Take 1 damage.</span></div>';

eldritchSharp = eldritchSharp.concat( eldritchMelee );
eldritchBlunt = eldritchBlunt.concat( eldritchMelee );

/*
 *	Eldritch Attacks (Monster)
 */

eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div class="text">The monster makes its special attack</div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The abomination strikes the ground, causing a tremor that throws you into the air.</span></div><div class="text">Each investigator in the room is dealt 1 damage.</div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">It speeds towards you like a freight train.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You quickly dive out of the way.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">Its body hammers into you with full force.</span> <span class="text">The monster damages you. The keeper may then move you 1 space.</span></div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">Its thoughts invade your mind.</span></div><div class="test">Test Willpower -1.</div><div><span class="passFail">Pass:</span> <span class="flavour">You steel your thoughts against its alien presence.</span> <span class="text">You may move 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You writhe in pleasure as it tries to swallow you.</span> <span class="text">The monster damages you.</span></div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The unspeakable horror wraps a tentacle around you and begins to squeeze.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You pry the tantacle off enough to free yourself.</span> <span class="text">Take 1 damage.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You feel your ribs breaking.</span> <span class="text">Take 3 damage and you are stunned.</span></div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The horrible thing is grabbing at your arms and legs with its repulsive tentacles.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You elude its grasp.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You are knocked to the floor.</span> <span class="text">Take 1 damage and you are stunned.</span></div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The horror creeps towards you.</span></div><div class="test">Test Strength.</div><div><span class="passFail">Pass:</span> <span class="flavour">You push yourself away, inadvertently touching the abomination.</span> <span class="text">Take 1 horror.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">A tentacle wraps around your leg.</span> <span class="text">Take 1 horror and the monster damages you.</span></div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">With alarming speed, the abomination tries to overwhelm you with its mass.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You narrowly avoid being crushed.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The thing pins you to the floor with its tremendous weight.</span> <span class="text">The monster damages you and you are stunned.</span></div>';
eldritchMonster[eldritchMonster.length] = '<div class="title">Monster Attack</div><div><span class="flavour">The abomination strikes, using its tentacle like a whip.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You duck out of harm\'s way.</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">The impact flings you into the air.</span> <span class="text">Take 2 damage and the keeper may move you 1 space.</span></div>';

eldritchHiding[eldritchHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">The abomination\'s tentacles seem to search every nook and cranny of the room.</span></div><div class="test">Test Dexterity.</div><div><span class="passFail">Pass:</span> <span class="flavour">You manage to evade its reach.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You realize, to your horror, that your hand is resting on a tentacle.</span> <span class="text">You are no longer hiding.</span></div>';
eldritchHiding[eldritchHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">From your hiding spot, you can see the horrific silhouette of the abomination.</span></div><div class="test">Test Willpower.</div><div><span class="passFail">Pass:</span> <span class="flavour">You close your eyes and keep yourself quiet.</span> <span class="text">Take 1 horror and move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You scream in terror.</span> <span class="text">Take 1 horror and you are no longer hiding.</span></div>';
eldritchHiding[eldritchHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">The abomination slowly rotates, searching the room with senses you cannot comprehend.</span></div><div class="test">Test Luck +1.</div><div><span class="passFail">Pass:</span> <span class="flavour">You remain undetected.</span> <span class="text">You may move the monster 1 space.</span></div><div><span class="passFail">Fail:</span> <span class="flavour">You feel it invading your mind.</span> <span class="text">Take 1 horror and you are no longer hiding.</span></div>';
eldritchHiding[eldritchHiding.length] = '<div class="title">Monster vs. Hiding</div><div><span class="flavour">It sees your body heat and attacks without missing a beat.</span></div><div class="text">You are no longer hiding. The monster attacks you again.</div>';

eldritchBarrier[eldritchBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The horrible thing smashes through the door, partially burying itself under the barrier.</span></div><div class="text">The barrier is destroyed.</div><div class="test">Test the monster\'s damage value +1.</div><div><span class="passFail">Pass:</span> <span class="text">No effect.</span></div><div><span class="passFail">Fail:</span> <span class="text">The monster is stunned.</span></div>';
eldritchBarrier[eldritchBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">It attempts to absorb the barrier into its body.</span></div><div class="test">Test the monster\'s health value.</div><div><span class="passFail">Pass:</span> <span class="text">The barrier is destroyed and the monster heals up to 2 damage.</span></div><div><span class="passFail">Fail:</span> <span class="text">No effect.</span></div>';
eldritchBarrier[eldritchBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The barrier is pulverized into a shower of wooden splinters.</span></div><div class="text">Every investigator and monster in the barrier\'s space is dealt 1 damage. The barrier is then destroyed.</div>';
eldritchBarrier[eldritchBarrier.length] = '<div class="title">Monster vs. Barrier</div><div><span class="flavour">The horror bursts through the door as if nothing had been in its path. Large splinters of wood are now imbedded in its body.</span></div><div class="text">The barrier is destroyed. Then deal 2 damage to the monster.</div>';